title: Monica Espitia # your name (or website title) here
logo: "/images/cv_2021.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  +4 years Experience in Predictive Modeling, Simulation and Optimization in Health and Automotive sector. Proficiency in  Python, Power BI, Tableau. Interested in ML and AI Healthcare applications.
  <br><br>
  <a href="https://www.linkedin.com/in/moanesga/">View My LinkedIn Profile</a>
  <br>
  <a href="https://www.kaggle.com/moanesga/">View My Kaggle Profile</a>
  <br><br>
 
theme: jekyll-theme-minimal
google_analytics: UA-180337592-1 # your Google Analytics tracking ID here
