title: Monica Espitia # your name (or website title) here
logo: "/images/monica(2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  +2 years Experience in Predictive Modeling and Optimization in Automotive and Health sector. 
  Data skills for Supply Chain projects using SQL, Python, MS Excel and SPSS. 
  Continuous learning on ML with focus Data Visualization, NLP and MS Azure .
  PM competencies as Sr. Admin at Intel and Quality Director of Colombian National Police pharmacies,
  HSEQ team head and Audit DB.

  <br><br>
  Competencies: data science, machine learning, data mining, SPSS/Python/R/Tableau/SQL/Pentaho, project management, business intelligence, e-learning development  
  <br><br>
  <a href="https://www.linkedin.com/in/moanesga/">View My LinkedIn Profile</a> 
   <br><br>
  <a href="https://github.com/moanesga/">View My GitHub Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
