title: Monica Espitia # your name (or website title) here
logo: "/images/Portfolio.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  +2 years Experience in Predictive Modeling and Optimization in Automotive and Health sector. 
  Supply Chain projects using SQL, Python, MS Excel and SPSS. 
  Interested in ML with focus Data Visualization Tableau, NLP and MS Azure.
   <br><br>
  <a href="https://github.com/moanesga/">View My GitHub Profile</a> 
   <br><br>
  <a href="https://www.linkedin.com/in/moanesga/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
google_analytics: UA-180337592-1 # your Google Analytics tracking ID here
