title: Monica Espitia # your name (or website title) here
logo: "/images/cv_2021_v2.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  AI & Analytics Consultant with +4 years experience in Analytics and Operations. I have accompanied Global IT, Automotive and Life Sciences customers to develop data strategies ad forecasting models. In the last years my focus has been on Tableau for Data Analytics.
  <br><br>
  Holds a Master's Degree in Project Management and Data Science from the HTW Berlin. Currently finishing a Diploma of Advanced Studies in Biomedical Informatics and Data Science at the Hochschule Mannheim.
  <br><br>
  Credentials: Tableau Certified Data Analyst, Tableau Desktop Specialist, Tableau Certified Associate Consultant, Salesforce Certified Associate
  <br><br>
  <a href="https://www.linkedin.com/in/moanesga/">View My LinkedIn Profile</a>
  <br>br>
  <a href="https://github.com/moanesga/">View My Github Profile</a>
  <br>br>
  <a href="https://www.kaggle.com/moanesga/">View My Kaggle Profile</a>
  <br><br>
 
theme: jekyll-theme-minimal
google_analytics: UA-180337592-1 # your Google Analytics tracking ID here
